import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 0,
  },
  loadingText: {
    fontSize: 18,
    textAlign: 'center',
    marginTop: 50,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
  },
  filterContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minWidth: 80,
  },
  filterIcon: {
    fontSize: 18,
  },
  filterButtonText: {
    fontSize: 14,
    fontWeight: '500',
    marginRight: 8,
  },
  chevronIcon: {
    fontSize: 12,
    color: '#6B7280',
  },
  dropdown: {
    position: 'absolute',
    top: 120,
    left: 16,
    right: 16,
    borderRadius: 8,
    borderWidth: 1,
    zIndex: 1000,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  dropdownText: {
    fontSize: 14,
  },
  priceFilterContainer: {
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
  },
  priceFilterLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  priceSliderContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  priceButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  priceButtonText: {
    fontSize: 12,
    fontWeight: '500',
  },
  tableContainer: {
    // Let content define width so we don't get a large empty gap
    alignSelf: 'flex-start',
    paddingBottom: 0,
    marginBottom: 0,
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 0,
    marginBottom: 6,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  headerCell: {
    width: 80,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  playerHeaderCell: {
    width: 150,
    alignItems: 'flex-start',
  },
  headerText: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  playersList: {
    flex: 1,
    paddingBottom: 0,
    marginBottom: 0,
  },
  playerRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 6,
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    // Add subtle border for better touch feedback
    borderWidth: 1,
    borderColor: 'transparent',
  },
  playerInfoCell: {
    width: 150,
    flexDirection: 'row',
    alignItems: 'center',
  },
  playerPhoto: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 8,
    // Use top portion of the image
    resizeMode: 'cover',
  },
  playerDetails: {
    flex: 1,
  },
  playerName: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  playerTeam: {
    fontSize: 10,
  },
  warningIcon: {
    fontSize: 16,
    marginLeft: 8,
  },
  starIcon: {
    fontSize: 16,
    marginLeft: 8,
  },
  statCell: {
    width: 80,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  statText: {
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  fixtureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 4,
    minHeight: 20,
  },
  fixtureText: {
    fontSize: 9,
    fontWeight: '600',
    textAlign: 'center',
  },
  loadingMoreContainer: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 0,
    alignItems: 'center',
  },
  loadingMoreText: {
    fontSize: 14,
    color: '#6B7280',
  },
  endOfListContainer: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 0,
    alignItems: 'center',
  },
  endOfListText: {
    fontSize: 14,
    color: '#6B7280',
  },
  playerCountContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 8,
    alignItems: 'center',
  },
  playerCountText: {
    fontSize: 14,
    fontWeight: '500',
  },
  clubDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  clubBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  xpStatusContainer: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
    alignItems: 'center',
  },
  xpStatusText: {
    fontSize: 14,
    fontWeight: '500',
  },
}); 